version: '3.8'

services:
  backend:
    build:
      context: ./backend
    restart: always
    environment:
      - REDIS_URL=${REDIS_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_S3_QUOTA_BYTES=${AWS_S3_QUOTA_BYTES}
      - SECRET_KEY=${SECRET_KEY}
      - OAUTH_AUTHORIZE_URL=${OAUTH_AUTHORIZE_URL}
      - OAUTH_TOKEN_URL=${OAUTH_TOKEN_URL}
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
